### ISSUE TITLE
Parser parses hex incorrectly

### ISSUE THREAD

**Issue by instagibbs** [tenthirtyone/blocktools#3]
https://github.com/tenthirtyone/blocktools/blob/master/blocktools.py#L37

Either use binascii.hexlify, or do '%02x' to make sure it prints the leading zeros. Otherwise it parses bad transactions/pubkeys quite often.

**Comment by tenthirtyone** [comment]
Thanks. I can make the change or if you'd like send a pull request

**Comment by instagibbs** [comment]
Sent. Thanks!
